name: Comby
on: [push, pull_request]
jobs:
  build:
    name: Comby test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run comby
        uses: comby-tools/comby-action@master
