name: Comby cron	
on: 	
  schedule:	
    - cron: '*/10 * * * *'	
jobs:	
  build:	
    name: Comby cron test	
    runs-on: ubuntu-latest	
    steps:	
      - uses: actions/checkout@v2	
      - name: Run comby	
        uses: comby-tools/comby-action@master	
      - name: Create PR	
        uses: peter-evans/create-pull-request@v3	
        with:	
          token: ${{ secrets.GITHUB_TOKEN }}	
          commit-message: 'Comby autofixes in Go files v2'	
          branch: comby-autofixes-v2	
